#:import Factory kivy.factory.Factory



# WINDOWS
WindowManager:
    FirstWindow:
    SecondWindow:
    ThirdWindow:
    FourthWindow:
    FifthWindow:
    SixthWindow:
    CalWindow:
    AreaWindow:
<mypopup>:
    id: pp
    size_hint:.4,.4
    title:'Close Alert(DMAPP)'
    BoxLayout:
        orientation:'vertical'
        Label:
            text:'Are you sure to exit the app!!!!'
            font_size:30
        BoxLayout:
            orientation:'horizontal'
            spacing: 10
            RoundedBtn:
                text:'Yes,Close'
                font_size:30
                back_color:(0.157,0.455,.753,1)
                size_hint:.5,.5
                on_release:app.close_app()
            RoundedBtn2:
                text:'No,Stay'
                font_size:30
                back_color:(0.157,0.455,.753,1)
                size_hint:.5,.5
                on_release:pp.dismiss()

<RoundedBtn@Button>:
    background_color:(0,0,0,0)
    background_normal:""
    #back_color:(1,0,1,1)
    #border_radius1:[18]
    canvas.before:
        Color:
            rgb: (0,.5,.9,1) if self.state == 'normal' else (.5,.6,.8,1)
        RoundedRectangle:

            radius:[18]
            size:self.size
            pos:self.pos
<RoundedBtn2@Button>:
    background_color:(0,0,0,0)
    background_normal:''

    #back_color:(1,0,1,1)
    #border_radius2:[18]
    canvas.before:

        Color:
            rgb: (.3,.5,.9,1) if self.state == 'normal' else (0,.4,.7, 1)

        RoundedRectangle:

            radius:[18]
            size:self.size
            pos:self.pos


#FIRST WINDOW
<FirstWindow>:
    name:'first'
    BoxLayout:
        orientation:'vertical'
        spacing:20
        padding:15
        size:root.width,root.height
        Label:
            text:'DM CALCULATOR'
            font_size:60
        GridLayout:
            size:root.width,root.height
            cols:2
            rows:2
            padding:15
            spacing:15
            Button:
                text:'Menu'

                font_size:40
                background_color:"#4c79ff87"
                on_release:
                    app.root.current='second'
                    root.manager.transition.direction='left'
            BoxLayout:
                orientation:'vertical'
                Button:
                    text:'Customize'

                    font_size:40
                    background_color:"#4c79ff87"
                    on_release:
                        app.root.current='third'
                        root.manager.transition.direction='left'

            Button:
                text:'Help'

                font_size:40
                background_color:"#4c79ff87"
                on_release:
                    app.root.current='fourth'
                    root.manager.transition.direction='left'
            Button:
                text:'Exit'
                font_size:40
                id: "x"
                on_release: root.openpopup()

                #:import Popup kivy.uix.popup

                #on_press: App.get_running_app().stop(); Window.close()
                ##on_release:
                #3    app.root.current='fifth'
                 #3   root.manager.transition.direction='left'
                background_color:"#bb4141b3"
        BoxLayout:
            orientation:'horizontal'
            padding:15
            spacing:20
            size:root.width,root.height
            font_size:40
            background_color:"#4c79ff87"
            Button:
                text:"About"
                font_size:40
                background_color:"#4c79ff87"
                on_release:
                    app.root.current='sixth'
                    root.manager.transition.direction='left'
###############################SECOND WINDOW#####################################################################################
<SecondWindow>:
    name:'second'


    BoxLayout:
        spacing:10
        padding:10
        orientation:'vertical'
        Label:
            text:'Menu'
            font_size: 50
        Button:
            text:'Calculator'
            font_size:40
            background_color:"#4c79ff87"
            on_release:


                app.root.current='calc'
                root.manager.transition.direction='left'
        Button:
            text:'Area'
            font_size:40
            background_color:"#4c79ff87"
            on_release:


                app.root.current='area'
                root.manager.transition.direction='left'
    AnchorLayout:
        anchor_x:'left'
        anchor_y:'top'
        Button:

            text:u'\u00AB'
            size_hint:.1,.1
            font_size:40
            background_color:"#00468057"
            background_active:'red'
            #foreground_color:
            on_release:


                app.root.current='first'
                root.manager.transition.direction='right'
<AreaWindow>:
    
    name: 'area'

    TabbedPanel:
        do_default_tab:False
        tab_width: self.parent.width/7.035
        background_color:"black"
# TRIANGLE AREA
        TabbedPanelItem:

            text:'Triangle'
            background_color:'#19a8ff86'
            background_normal:"white"
            BoxLayout:
                background_color:"black"
                orientation:'vertical'
                BoxLayout:
                    orientation:'horizontal'
                    padding:15
                    spacing_y:5
                    spacing_x:5
                    background_color:"black"
                    BoxLayout:
                        orientation:'vertical'
                        background_color:"black"
                        BoxLayout:
                            background_color:"black"
                            orientation:'vertical'
                            padding:20
                            spacing:5
                            size_hint:1,.5
                            id:t_canvas
                            t_color:(0,1,1)
                            t_color1:(1,1,1)
                            t_color2:(1,1,1)

                            canvas:
                                Color:
                                    rgb:self.t_color
                                #base1 ain't seeing nothin'
                                Line:
                                    points:(self.width/3,self.height/2+200,self.width/4+230,self.height/2+200)
                                    width:2
                                Color:
                                    rgb:self.t_color1
                                Line:
                                    points:(self.width/3,self.height/2+200,self.width/3+50,self.height/2+270)
                                    width:2
                                Color:
                                    rgb:(1,1,1)
                                Line:
                                    points:(self.width/3+50,self.height/2+270,self.width/3+50,self.height/2+200)
                                    width:1.5
                                Color:
                                    rgb:self.t_color2
                                Line:
                                    points:(self.width/3+50,self.height/2+270,self.width/4+230,self.height/2+200)
                                    width:2
                            Label:
                                text:
                            BoxLayout:
                                background_color:"black"
                                orientation:'vertical'
                                Label:
                                    text:
                                BoxLayout:
                                    background_color:"black"
                                    orientation:'horizontal'
                                    Label:
                                        text:'s=([i][b][size=24][color=#04d3ff]a[/color][/size][/i][/b]+b+c)/2'
                                        markup:True
                                        id:for_t
                                        font_size:20
                                    Label:
                                        text:'A=√(s-[i][b][size=24][color=#04d3ff]a[/color][/size][/i][/b])(s-b)(s-c)'
                                        markup:True
                                        id:for_t1
                                        font_size:20
                            BoxLayout:
                                background_color:"black"
                                orientation:'horizontal'


                                GridLayout:
                                    cols:2
                                    rows:3
                                    spacing:3
                                    background_color:"black"


                                    CheckBox:
                                        group:'tcheckbox'
                                        size_hint:.1,.1
                                        id:chk
                                        active:True
                                        on_active:root.t_change(self.active)

                                    TextInput:
                                        text_filter:'float'
                                        id:a
                                        size_hint:1,.15
                                        disabled: not chk.active

                                        hint_text:'Enter the value of side A (m)'
                                        background_color:'#1936ff25'
                                        disabled_foreground_color:'#00ffffff'
                                        foreground_color:'#00ffffff'
                                        disabled_hint_text_color:"00ffffff"
                                        hint_text_color:"grey"
                                        font_size:25

                                    CheckBox:


                                        size_hint:.1,.1
                                        group:'tcheckbox'
                                        id:chk1
                                        on_active:root.t_change1(self.active)

                                    TextInput:
                                        text_filter:'float'
                                        id:b
                                        size_hint:1,.15
                                        disabled: not chk1.active
                                        background_color:'#1936ff25'
                                        disabled_foreground_color:'#00ffffff'
                                        foreground_color:'#00ffffff'
                                        disabled_hint_text_color:"00ffffff"
                                        hint_text_color:"grey"
                                        font_size:25

                                        hint_text:'Enter the value of side B (m)'

                                    CheckBox:
                                        size_hint:.1,.1
                                        id:chk2
                                        group:'tcheckbox'
                                        on_active:root.t_change2(self.active)

                                    TextInput:
                                        text_filter:'float'
                                        id:c
                                        hint_text:'Enter the value of side C (m)'
                                        font_size:25

                                        size_hint:1,.15
                                        disabled: not chk2.active
                                        background_color:'#1936ff25'
                                        disabled_foreground_color:'#00ffffff'
                                        foreground_color:'#00ffffff'
                                        disabled_hint_text_color:"00ffffff"
                                        hint_text_color:"grey"
                                        font_name:"arial"
                            BoxLayout:
                                orientation:'horizontal'

                                TextInput:
                                    hint_text:'00'
                                    size_hint:1,.35
                                    disabled:True
                                    id:ans
                                    #font_size:20
                                    multiline:False
                                    background_color:'#1936ff25'
                                    disabled_foreground_color:'#00ffffff'
                                    font_size:35
                                
                            #Label:
                                #id:label
                                #pos_hint:{'x':.3}
                               
                            
                                
                       
                                                 
                        
                            
                            
                        
                            
                    BoxLayout:
                        background_color:"black"
                        orientation:'vertical'
                        BoxLayout:
                            background_color:"black"
                            orientation:'horizontal'
                            size_hint:1,.2
                            
                            Button:
                                text:'CE'
                                on_press:root.al_clr()
                                background_color:'#963232ff'
                                color:'#ff1919ff'
                                font_size:45

                            Button:
                                text:'C'
                                on_press:root.tri_back()
                                background_color:'#713232ff'
                                color:'#ff3232ff'
                                font_size:45
                           
                        GridLayout:
                            cols:3
                            rows:4
                            background_color:"black"
                            Button:
                               
                                text:'1'
                                #on_release:root.ids.c_inp.focused=True
                                on_press:root.get_value('1')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                       
                            Button:
                                text:'2'
                                on_press:root.get_value('2')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                
                                text:'3'
                                on_press:root.get_value('3')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'4'
                                on_press:root.get_value('4')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'5'
                                on_press:root.get_value('5')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'6'
                                on_press:root.get_value('6')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'7'
                                on_press:root.get_value('7')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'8'
                                on_press:root.get_value('8')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'9'
                                on_press:root.get_value('9')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'0'
                                on_press:root.get_value('0')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                                
                            Button:
                                text:'.'
                                on_press:root.point()
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'='
                                on_press:root.answers()
                                background_color:'#194a9886'
                                color:'#00ffffff'
                                font_size:45
                       
                
                    
                Button:
                    text:'Back'
                    size_hint:1,.15
                    background_color:"#1954c787"
                    font_size:40
                    on_press:
                        root.ids.tra_inp.text=''
                        root.ids.tra_inp1.text=''
                        root.ids.tra_inp2.text=''
                        root.ids.tra_ans.text=''
                        root.ids.tra_chk.active=True
                        root.ids.inpr.text=''
                        root.ids.inpr1.text=''
                        root.ids.rans.text=''
                        root.ids.rchk.active=True
                        root.ids.a.text='' 
                        root.ids.b.text='' 
                        root.ids.c.text=''
                        root.ids.ans.text=''
                        root.ids.chk.active=True
                    #on_press:root.ids.chk1.active=False
                    #on_press:root.ids.chk2.active=False
                    on_release:
                        app.root.current='second'
                        root.manager.transition.direction='right'
            

           

       
            
# RECTANGLE AREA
        TabbedPanelItem:
            text:'Rectangle'
            background_color:'#19a8ff86'
            background_normal:"white"
            
            BoxLayout:
                orientation:'vertical'
                BoxLayout:
                    padding:15
                    spacing_y:5
                    spacing_x:5
                    BoxLayout:
                       
                        orientation:'vertical'
                        padding:20
                        spacing:10
                        
                            
                        #Image:
                            #source:'rec.png'
                        
                     
                        id: w_canvas
                        my_color: (0, 1, 1)
                        my_color2:(1,1,1)
                        canvas:
                            
                            
                            Color:
                                rgb: self.my_color
                            Line:
                                points:(self.width/4,self.height/2+200,self.width/4+200,self.height/2+200)
                                width:2
                                
                            Color:
                                rgb: self.my_color2  
                            Line:
                                points:(self.width/4+200,self.height/2+200,self.width/4+200,self.height/2+300)
                                width:2
                            Color:
                                rgb: self.my_color
                            Line:
                                points:(self.width/4+200,self.height/2+300,self.width/4,self.height/2+300)
                                width:2
                            Color:
                                rgb: self.my_color2
                                
                            
                            Line:
                                points:(self.width/4,self.height/2+300,self.width/4,self.height/2+200)
                                width:2
                        Label:
                            text:
                        BoxLayout:
                            orientation:'vertical'
                            Label:
                                text:
                            Label:
                                text:'A=[color=#04d3ff][size=34][i][b]L[/b][/i][/color][/size]XW'
                                markup:True
                                id:for_rec
                                font_size:30




                        
                        BoxLayout:
                            orientation:'horizontal'
                            
                            GridLayout:
                                cols:2
                                rows:2
                                spacing:10
                                CheckBox:
                                    id:rchk
                                    size_hint:.1,.1
                                    group:'rcheckbox'
                                    active:True
                                    on_active:root.change1(self.active)
                                TextInput:
                                    id:inpr
                                    size_hint:1,.15
                                    text_filter:'float'
                                    disabled: not rchk.active
                                    hint_text:'enter length(m)'
                                    background_color:'#1936ff25'
                                    disabled_foreground_color:'#00ffffff'
                                    foreground_color:'#00ffffff'
                                    disabled_hint_text_color:"00ffffff"
                                    hint_text_color:"grey"
                                    font_name:"arial"
                                    font_size:25
                                CheckBox:
                                    id:rchk1
                                    size_hint:.1,.1
                                    group:'rcheckbox'
                                    on_active:root.change2(self.active)
                                TextInput:
                                    id:inpr1
                                    size_hint:1,.15
                                    text_filter:'float'
                                    disabled: not rchk1.active
                                    hint_text:'enter width(m)'
                                    background_color:'#1936ff25'
                                    disabled_foreground_color:'#00ffffff'
                                    foreground_color:'#00ffffff'
                                    disabled_hint_text_color:"00ffffff"
                                    hint_text_color:"grey"
                                    font_name:"arial"
                                    font_size:25
                        BoxLayout:
                                
                            TextInput:
                                hint_text:'00'
                                size_hint:1,.5
                                disabled:True
                                id:rans
                                #font_size:20
                                multiline:False
                                background_color:'#1936ff25'
                                disabled_foreground_color:'#00ffffff'
                                font_size:35
                                
                    BoxLayout:
                        orientation:'vertical'
                        BoxLayout:
                            orientation:'horizontal'
                            size_hint:1,.2
                            Button:
                                text:'CE'
                                on_press:root.rec_all_clr()
                                background_color:'#963232ff'
                                color:'#ff1919ff'
                                font_size:45
                            Button:
                                text:'C'
                                on_press:root.rec_del()
                                background_color:'#713232ff'
                                color:'#ff3232ff'
                                font_size:45
                        GridLayout:
                            cols:3
                            rows:4
                            #row1
                            Button:
                                text:'7'
                                on_press:root.get_valuer('7')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'8'
                                on_press:root.get_valuer('8')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'9'
                                on_press:root.get_valuer('9')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            #row2
                            Button:
                                text:'4'
                                on_press:root.get_valuer('4')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'5'
                                on_press:root.get_valuer('5')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'6'
                                on_press:root.get_valuer('6')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            #row3
                            Button:
                                text:'1'
                                on_press:root.get_valuer('1')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'2'
                                on_press:root.get_valuer('2')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'3'
                                on_press:root.get_valuer('3')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            #row4
                            Button:
                                text:'0'
                                on_press:root.get_valuer('0')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'.'
                                on_press:root.rec_dot()
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'='
                                on_press:root.area_rec()
                                background_color:'#194a9886'
                                color:'#00ffffff'
                                font_size:45


                Button:
                    size_hint:1,.15
                    text:'Back'
                    background_color:"#1954c787"
                    font_size:40
                    on_press:
                        root.ids.tra_inp.text=''
                        root.ids.tra_inp1.text=''
                        root.ids.tra_inp2.text=''
                        root.ids.tra_ans.text=''
                        root.ids.tra_chk.active=True
                        root.ids.inpr.text=''
                        root.ids.inpr1.text=''
                        root.ids.rans.text=''
                        root.ids.rchk.active=True
                        root.ids.a.text='' 
                        root.ids.b.text='' 
                        root.ids.c.text=''
                        root.ids.ans.text=''
                        root.ids.chk.active=True
                        root.ids.w_canvas.my_color = (0, 1, 1)
                       # root.ids.for_rec.text="A=[size=20][color=#04d3ff][i][b]L[/b][/i][/color][/size]XW"
                        #root.ids.rchk1.active=False
                    on_release:
                        app.root.current='second'
                        root.manager.transition.direction='right'
          
            

# TRAPEZIUM AREA
        TabbedPanelItem:
            text:'Trapezium'
            background_color:'#19a8ff86'
            background_normal:"white"
            BoxLayout:
                orientation:'vertical'
                BoxLayout:
                    orientation:'horizontal'
                    padding:15
                    spacing_y:5
                    spacing_x:5
                    BoxLayout:
                        orientation:'vertical'
                        BoxLayout:
                            orientation:'vertical'
                            padding:20
                            spacing:5
                            size_hint:1,.5
                            id:w_canvas1
                            tra_color:(0,1,1)
                            tra_color1:(1,1,1)
                            tra_color2:(1,1,1)
                            
                            canvas:
                                Color:
                                    rgb:self.tra_color
                                #base1 ain't seeing nothin'
                                Line:
                                    points:(self.width/3,self.height/2+300,self.width/4+150,self.height/2+300)
                                    width:2
                                Color:
                                    rgb:self.tra_color1
                                #right height
                                Line:
                                    points:(self.width/4+150,self.height/2+300,self.width/4+150,self.height/2+225)
                                    width:2
                                #left height

                                Line:
                                    points:(self.width/3,self.height/2+300,self.width/3,self.height/2+225)
                                    width:2
                                Color:
                                    rgb:self.tra_color2
                                #base2
                                Line:
                                    points:(self.width/3-70,self.height/2+225,self.width/4+220,self.height/2+225)
                                    width:2
                                
                                #left leg
                                Color:
                                    rgb:(1,1,1)
                                Line:
                                    points:(self.width/3,self.height/2+300,self.width/3-70,self.height/2+225)
                                    width:2
                                #right leg
                                Line:
                                    points:(self.width/4+150,self.height/2+300,self.width/4+220,self.height/2+225)
                                    width:2
                            Label:
                                text:
                            BoxLayout:
                                orientation:'vertical'
                                Label:
                                    text:
                                Label:
                                    text:'A=1/2([size=34][color=#04d3ff][i][b]b[/i][/b][/color][/size][sub][color=#04d3ff][size=20][i][b]1[/b][/i][/size][/sub][/color]+b[sub][size=20]2[/size][/sub])h'
                                    markup:True
                                    id:for_tra
                                    font_size:30
                            BoxLayout:
                                orientation:'horizontal'
                                GridLayout:
                                    cols:2
                                    rows:3
                                    spacing:3
                                    CheckBox:
                                        id:tra_chk
                                        size_hint:.1,.1
                                        group:'tra_chks'
                                        active:True
                                        on_active:root.tra_change(self.active)
                                    TextInput:
                                        disabled: not tra_chk.active
                                        id:tra_inp
                                        text_filter:'float'
                                        multiline:False
                                        hint_text:'enter base1(m)'
                                        background_color:'#1936ff25'
                                        disabled_foreground_color:'#00ffffff'
                                        foreground_color:'#00ffffff'
                                        disabled_hint_text_color:"00ffffff"
                                        hint_text_color:"grey"
                                        font_name:"arial"
                                        font_size:25
                                    CheckBox:
                                        group:'tra_chks'
                                        id:tra_chk1
                                        size_hint:.1,.1
                                        on_active:root.tra_change1(self.active)
                                    TextInput:
                                        disabled: not tra_chk1.active
                                        id:tra_inp1
                                        text_filter:'float'
                                        multiline:False
                                        hint_text:'enter base2(m)'
                                        background_color:'#1936ff25'
                                        disabled_foreground_color:'#00ffffff'
                                        foreground_color:'#00ffffff'
                                        disabled_hint_text_color:"00ffffff"
                                        hint_text_color:"grey"
                                        font_name:"arial"
                                        font_size:25
                                    CheckBox:
                                        group:'tra_chks'
                                        id:tra_chk2
                                        size_hint:.1,.1
                                        on_active:root.tra_change2(self.active)
                                    TextInput:
                                        disabled: not tra_chk2.active
                                        id:tra_inp2
                                        text_filter:'float'
                                        multiline:False
                                        hint_text:'enter height(m)'
                                        background_color:'#1936ff25'
                                        disabled_foreground_color:'#00ffffff'
                                        foreground_color:'#00ffffff'
                                        disabled_hint_text_color:"00ffffff"
                                        hint_text_color:"grey"
                                        font_name:"arial"
                                        font_size:25
                            BoxLayout:
                                orientation:'horizontal'
                                    
                                TextInput:
                                    hint_text:'00'
                                    size_hint:1,.35
                                    disabled:True
                                    id:tra_ans
                                                          #font_size:20
                                    multiline:False
                                    background_color:'#1936ff25'
                                    disabled_foreground_color:'#00ffffff'
                                    font_size:35
                    BoxLayout:
                        orientation:'vertical'
                        BoxLayout:
                            size_hint:1,.2
                            orientation:'horizontal'
                            Button:
                                text:'CE'
                                on_press:root.tra_all_clr()
                                background_color:'#963232ff'
                                color:'#ff1919ff'
                                font_size:45
                            Button:
                                text:'C'
                                on_press:root.tra_back()
                                background_color:'#713232ff'
                                color:'#ff3232ff'
                                font_size:45
                        GridLayout:
                            cols:3
                            rows:4
                            #row1
                            Button:
                                text:'7'
                                on_press:root.tra_get_value('7')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'8'
                                on_press:root.tra_get_value('8')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'9'
                                on_press:root.tra_get_value('9')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            #row2
                            Button:
                                text:'4'
                                on_press:root.tra_get_value('4')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'5'
                                on_press:root.tra_get_value('5')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'6'
                                on_press:root.tra_get_value('6')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            #row3
                            Button:
                                text:'1'
                                on_press:root.tra_get_value('1')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'2'
                                on_press:root.tra_get_value('2')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'3'
                                on_press:root.tra_get_value('3')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            #row4
                            Button:
                                text:'0'
                                on_press:root.tra_get_value('0')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'.'
                                on_press:root.tra_dot()
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'='
                                on_press:root.tra_ans()
                                background_color:'#194a9886'
                                color:'#00ffffff'
                                font_size:45
                        
                        
                        
                Button:
                    size_hint:1,.15
                    text:'Back'
                    background_color:"#1954c787"
                    font_size:40
                    on_press:
                        root.ids.tra_inp.text=''
                        root.ids.tra_inp1.text=''
                        root.ids.tra_inp2.text=''
                        root.ids.tra_ans.text=''
                        root.ids.tra_chk.active=True
                        root.ids.inpr.text=''
                        root.ids.inpr1.text=''
                        root.ids.rans.text=''
                        root.ids.rchk.active=True
                        root.ids.a.text='' 
                        root.ids.b.text='' 
                        root.ids.c.text=''
                        root.ids.ans.text=''
                        root.ids.chk.active=True
                        #root.ids.tra_chk1.active=False
                        #root.ids.tra_chk2.active=False
                    on_release:
                        app.root.current='second'
                        root.manager.transition.direction='right'
      #################################################################3
      #################################################################
      ############RHOMBUS###########################################3



        TabbedPanelItem:
            text:'Rhombus'
            background_color:'#19a8ff86'
            background_normal:"white"
            BoxLayout:
                orientation:'vertical'
                BoxLayout:
                    orientation:'horizontal'
                    padding:15
                    spacing_y:5
                    spacing_x:5
                    BoxLayout:
                        orientation:'vertical'
                        padding:20
                        spacing:10
                    #canvas##3333333333333333333333333333333333333333333333333333333
                        id:rhom_cnvs
                        rhom_d1_color:(0,1,1)
                        rhom_d2_color:(1,1,1)
                        rhom_color:(1,1,1)

                        canvas:
                            Color:
                                rgb:self.rhom_color

                            Line: ##uperleft side
                                points:(self.width/3,self.height/2+280,self.width/3-70,self.height/2+200)
                                width:2
                            Line:##uper right
                                points:(self.width/3,self.height/2+280,self.width/3+70,self.height/2+200)
                                width:2
                            Line:##lower right
                                points:(self.width/3+70,self.height/2+200,self.width/3,self.height/2+120)
                                width:2
                            Line:#lower left
                                points:(self.width/3-70,self.height/2+200,self.width/3,self.height/2+120)
                                width:2
                            Color:
                                rgb:self.rhom_d1_color
                            Line:##diagonal1
                                points:(self.width/3,self.height/2+280,self.width/3,self.height/2+120)
                                width:1.5
                            Color:
                                rgb:self.rhom_d2_color
                            Line:##diaogonal2
                                points:(self.width/3-70,self.height/2+200,self.width/3+70,self.height/2+200)
                                width:1.5

                        Label:
                            text:''
                        BoxLayout:
                            orientation:'horizontal'
                            Label:
                                text:
                            Label:
                                text:
                        BoxLayout:
                            orientation:'vertical'

                            Label:
                                text:'A=1/2([color=#04d3ff][size=34][i][b]d[sub][color=#04d3ff][size=15][b][i]1[/color][/b][/i][/size][/sub][/b][/i][/color][/size]d2)'
                                markup:True
                                id:for_rhom
                                font_size:30
                        BoxLayout:
                            orientation:'horizontal'
                            BoxLayout:
                                orientation:'horizontal'
                                GridLayout:
                                    cols:2
                                    rows:2
                                    padding:5
                                    size:root.width/2-200,root.height
                                    CheckBox:
                                        size_hint:.1,.1
                                        group:'rhom_grp'
                                        id: rhom_chk_id1
                                        active:True
                                        on_active:root.rhom_change1(self.active)
                                    TextInput:
                                        font_size:20
                                        id:rhom_inp1
                                        disabled:not rhom_chk_id1.active
                                        hint_text:"Enter value of base(m)"
                                        text_filter:'float'
                                        background_color:'#1936ff25'
                                        disabled_foreground_color:'#00ffffff'
                                        foreground_color:'#00ffffff'
                                        disabled_hint_text_color:"00ffffff"
                                        hint_text_color:"grey"
                                        font_name:"arial"
                                        font_size:25
                                    CheckBox:
                                        size_hint:.1,.1
                                        group:'rhom_grp'
                                        id: rhom_chk_id2
                                        active:True
                                        on_active:root.rhom_change2(self.active)
                                    TextInput:
                                        font_size:20
                                        id:rhom_inp2
                                        disabled:not rhom_chk_id2.active
                                        hint_text:"Enter value of height(m)"
                                        text_filter:'float'
                                        background_color:'#1936ff25'
                                        disabled_foreground_color:'#00ffffff'
                                        foreground_color:'#00ffffff'
                                        disabled_hint_text_color:"00ffffff"
                                        hint_text_color:"grey"
                                        font_name:"arial"
                                        font_size:25
                        BoxLayout:

                            TextInput:
                                hint_text:'00'
                                size_hint:1,.7
                                disabled:True
                                id:rhom_ans
                                #font_size:20
                                multiline:False
                                background_color:'#1936ff25'
                                disabled_foreground_color:'#00ffffff'
                                font_size:35

                    BoxLayout:
                        orientation:"vertical"

                        BoxLayout:
                            orientation:'horizontal'
                            size_hint:1,.2
                            Button:
                                text:'CE'
                                on_press:root.rhom_allclr()
                                background_color:'#963232ff'
                                color:'#ff1919ff'
                                font_size:45
                            Button:
                                text:'C'
                                on_press:root.rhom_back()
                                background_color:'#713232ff'
                                color:'#ff3232ff'
                                font_size:45
                        GridLayout:
                            cols:3
                            rows:4
                            Button:
                                text:'7'
                                on_press:root.get_value_rhombus('7')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'8'
                                on_press:root.get_value_rhombus('8')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'9'
                                on_press:root.get_value_rhombus('9')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            #row2
                            Button:
                                text:'4'
                                on_press:root.get_value_rhombus('4')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'5'
                                on_press:root.get_value_rhombus('5')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'6'
                                on_press:root.get_value_rhombus('6')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            #row3
                            Button:
                                text:'1'
                                on_press:root.get_value_rhombus('7')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'2'
                                on_press:root.get_value_rhombus('2')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'3'
                                on_press:root.get_value_rhombus('3')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            #row4
                            Button:
                                text:'0'
                                on_press:root.get_value_rhombus('0')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'.'
                                on_press:root.rhom_dot()
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'='
                                on_press:root.rhom_answer()
                                background_color:'#194a9886'
                                color:'#00ffffff'
                                font_size:45
                Button:
                    text:'Back'
                    size_hint:1,.15
                    background_color:"#1954c787"
                    font_size:40
                    on_release:
                        app.root.current='second'
                        root.manager.transition.direction='right'


        TabbedPanelItem:
            text:'Parallelogram'
            background_color:'#19a8ff86'
            background_normal:"white"
            BoxLayout:
                orientation:"vertical"
                BoxLayout:
                    orientation:"horizontal"
                    padding:15
                    spacing_y:5
                    spacing_x:5
                    BoxLayout:
                        orientation:'vertical'
                        padding:20
                        spacing:10
                    #canvas##3333333333333333333333333333333333333333333333333333333
                        id:par_id
                        len_color_par:(0,1,1)
                        width_color_par:(1,1,1)
                        par_height:(1,1,1)
                        canvas:
                            Color:
                                rgb:self.len_color_par
                            Line: ###lower lengh
                                points:(self.width/4,self.height/2+200,self.width/4+200,self.height/2+200)
                                width:2
                            Color:
                                rgb:self.width_color_par
                            Line: ##left width
                                points:(self.width/4,self.height/2+200,self.width/4+60,self.height/2+290)
                                width:2
                            Color:
                                rgb:self.len_color_par
                            Line: ##upper leng
                                points:(self.width/4+60,self.height/2+290,self.width/4+250,self.height/2+290)
                                width:2
                            Color:
                                rgb:self.width_color_par
                            Line:##right widt
                                points:(self.width/4+250,self.height/2+290,self.width/4+200,self.height/2+200)
                                width:2
                            Color:
                                rgb:self.par_height
                            Line:##heigtht
                                points:(self.width/4+60,self.height/2+290,self.width/4+60,self.height/2+200)
                                width:2
                        Label:
                            text:''
                        BoxLayout:
                            orientation:'horizontal'
                            Label:
                                text:
                            Label:
                                text:
                        BoxLayout:
                            orientation:'vertical'

                            Label:
                                text:'A=[color=#04d3ff][size=34][i][b]b[/b][/i][/color][/size]h'
                                markup:True
                                id:for_par
                                font_size:30
                        BoxLayout:
                            orientation:'horizontal'
                            BoxLayout:
                                orientation:'horizontal'
                                GridLayout:
                                    cols:2
                                    rows:2
                                    padding:5
                                    size:root.width/2-200,root.height
                                    CheckBox:
                                        size_hint:.1,.1
                                        group:'par_chk1'
                                        id: par_id1
                                        active:True
                                        on_active:root.para_change1(self.active)
                                    TextInput:
                                        font_size:20
                                        id:par_inp1
                                        disabled:not par_id1.active
                                        hint_text:"Enter value of base(m)"
                                        text_filter:'float'
                                        background_color:'#1936ff25'
                                        disabled_foreground_color:'#00ffffff'
                                        foreground_color:'#00ffffff'
                                        disabled_hint_text_color:"00ffffff"
                                        hint_text_color:"grey"
                                        font_name:"arial"
                                        font_size:25
                                    CheckBox:
                                        size_hint:.1,.1
                                        group:'par_chk1'
                                        id: par_id2
                                        active:True
                                        on_active:root.para_change2(self.active)
                                    TextInput:
                                        font_size:20
                                        id:par_inp2
                                        disabled:not par_id2.active
                                        hint_text:"Enter value of height(m)"
                                        text_filter:'float'
                                        background_color:'#1936ff25'
                                        disabled_foreground_color:'#00ffffff'
                                        foreground_color:'#00ffffff'
                                        disabled_hint_text_color:"00ffffff"
                                        hint_text_color:"grey"
                                        font_name:"arial"
                                        font_size:25
                        BoxLayout:

                            TextInput:
                                hint_text:'00'
                                size_hint:1,.7
                                disabled:True
                                id:para_ans
                                font_size:20
                                multiline:False
                                background_color:'#1936ff25'
                                disabled_foreground_color:'#00ffffff'
                                font_size:35


                    BoxLayout:
                        orientation:"vertical"

                        BoxLayout:
                            orientation:'horizontal'
                            size_hint:1,.2
                            Button:
                                text:'CE'
                                on_press:root.para_allclr()
                                background_color:'#963232ff'
                                color:'#ff1919ff'
                                font_size:45
                            Button:
                                text:'C'
                                on_press:root.para_delete()
                                background_color:'#713232ff'
                                color:'#ff3232ff'
                                font_size:45
                        GridLayout:
                            cols:3
                            rows:4
                            Button:
                                text:'7'
                                on_press:root.para_get_value('7')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'8'
                                on_press:root.para_get_value('8')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'9'
                                on_press:root.para_get_value('9')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            #row2
                            Button:
                                text:'4'
                                on_press:root.para_get_value('4')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'5'
                                on_press:root.para_get_value('5')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'6'
                                on_press:root.para_get_value('6')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            #row3
                            Button:
                                text:'1'
                                on_press:root.para_get_value('7')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'2'
                                on_press:root.para_get_value('2')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'3'
                                on_press:root.para_get_value('3')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            #row4
                            Button:
                                text:'0'
                                on_press:root.para_get_value('0')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'.'
                                on_press:root.para_dot()
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'='
                                on_press:root.para_area()
                                background_color:'#194a9886'
                                color:'#00ffffff'
                                font_size:45
                Button:
                    text:'Back'
                    size_hint:1,.15
                    on_release:
                        app.root.current='second'
                        root.manager.transition.direction='right'
                    background_color:"#1954c787"
                    font_size:40










        TabbedPanelItem:
            text:'Circle'
            background_color:'#19a8ff86'
            background_normal:"white"
            BoxLayout:
                orientation:'vertical'
                BoxLayout:
                    orientation:'horizontal'
                    padding:15
                    spacing_y:5
                    spacing_x:5
                    BoxLayout:
                        orientation:'vertical'
                        padding:20
                        spacing:10

                    #Button:
                        #text:'b1'
                        id:cir_cnvs
                        cir_rad_color:(0,1,1)
                        cir_color:(1,1,1)
                        canvas:
                            Color:
                                rgb:self.cir_color
                            Line:
                                circle:(self.width/3+30,self.height/2+200,60)
                                width:1.5
                            Line:
                                points:(self.width/3-30,self.height/2+200,self.width/3+90,self.height/2+200)
                                width:1.2
                            Color:
                                rgb:self.cir_rad_color
                            Line:
                                points:(self.width/3+25,self.height/2+200,self.width/3+67,self.height/2+247)
                                width:1.2
                        Label:
                            text:''
                        BoxLayout:
                            orientation:'horizontal'
                            Label:
                                text:
                            Label:
                                text:
                        BoxLayout:
                            orientation:'vertical'

                            Label:
                                text:'A=π[b][i][color=#04d3ff][size=34]r²[/b][/i][/color][/size]'
                                markup:True
                                id:for_cir
                                font_size:30
                        BoxLayout:
                            orientation:'horizontal'
                            BoxLayout:
                                orientation:'horizontal'
                                GridLayout:
                                    cols:2
                                    rows:1
                                    padding:5
                                    size:root.width/2-200,root.height
                                    CheckBox:
                                        size_hint:.1,.1
                                        group:'cir_chk'
                                        id: cir_id
                                        active:True
                                        on_active:root.cir_change_color(self.active)
                                    TextInput:
                                        font_size:20
                                        id:cir_inp
                                        disabled:not cir_id.active
                                        hint_text:"Enter value of radius(m)"
                                        background_color:'#1936ff25'
                                        disabled_foreground_color:'#00ffffff'
                                        foreground_color:'#00ffffff'
                                        disabled_hint_text_color:"00ffffff"
                                        hint_text_color:"grey"
                                        font_name:"arial"
                                        font_size:25
                        BoxLayout:

                            TextInput:
                                hint_text:'00'
                                size_hint:1,.7
                                disabled:True
                                id:cir_ans
                                font_size:20
                                multiline:False
                                background_color:'#1936ff25'
                                disabled_foreground_color:'#00ffffff'
                                font_size:35

                    BoxLayout:
                        orientation:'vertical'
                        BoxLayout:
                            orientation:'horizontal'
                            size_hint:1,.2
                            Button:
                                text:'CE'
                                on_press:root.cir_alcr()
                                background_color:'#963232ff'
                                color:'#ff1919ff'
                                font_size:45

                            Button:
                                text:'C'
                                on_press:root.cir_back()
                                background_color:'#713232ff'
                                color:'#ff3232ff'
                                font_size:45
                        GridLayout:
                            cols:3
                            rows:4
                            Button:
                                text:'7'
                                on_press:root.cir_get_value('7')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'8'
                                on_press:root.cir_get_value('8')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'9'
                                on_press:root.cir_get_value('9')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            #row2
                            Button:
                                text:'4'
                                on_press:root.cir_get_value('4')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'5'
                                on_press:root.cir_get_value('5')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'6'
                                on_press:root.cir_get_value('6')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            #row3
                            Button:
                                text:'1'
                                on_press:root.cir_get_value('7')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'2'
                                on_press:root.cir_get_value('2')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'3'
                                on_press:root.cir_get_value('3')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            #row4
                            Button:
                                text:'0'
                                on_press:root.cir_get_value('0')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'.'
                                on_press:root.cir_dot()
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'='
                                on_press:root.cir_ans()
                                background_color:'#194a9886'
                                color:'#00ffffff'
                                font_size:45








                Button:
                    text:'Back'
                    background_color:"#1954c787"
                    font_size:40
                    size_hint:1,.15
                    on_release:
                        app.root.current='second'
                        root.manager.transition.direction='right'








#SPHERE AREA
        TabbedPanelItem:
            text:'Sphere'
            background_color:'#19a8ff86'
            background_normal:"white"
            BoxLayout:
                orientation:'vertical'
                BoxLayout:
                    orientation:'horizontal'
                    padding:15
                    spacing_y:5
                    spacing_x:5
                    BoxLayout:
                        orientation:'vertical'
                        padding:20
                        spacing:10
                        sp_rad_color:(0,1,1)
                        sp_color:(1,1,1)
                        id:sp_cnvs
                        canvas:
                            Color:
                                rgb:self.sp_color
                            Line:
                                circle:(self.width/3+30,self.height/2+200,60)
                                width:1.5
                            Line:
                                points:(self.width/3-30,self.height/2+200,self.width/3+90,self.height/2+200)
                                width:1.2
                            Line:
                                width:1.2
                                ellipse:(self.width/3-30,self.height/2+190,120,20)
                            #radius
                            Color:
                                rgb:self.sp_rad_color
                            Line:
                                points:(self.width/3+25,self.height/2+200,self.width/3+67,self.height/2+247)
                                width:1.2
                        Label:
                            text:''
                        BoxLayout:
                            orientation:'horizontal'
                            Label:
                                text:
                            Label:
                                text:

                        BoxLayout:
                            orientation:'vertical'

                            Label:
                                text:'A=4π[b][i][size=34][color=#04d3ff]r[/i][/b][/color][/size][sup][color=#04d3ff][size=20]2[/size][/color][/sup]'
                                markup:True
                                id:for_sp
                                font_size:30
                        BoxLayout:
                            orientation:'horizontal'




                            BoxLayout:
                                orientation:'horizontal'


                                GridLayout:
                                    cols:2
                                    rows:1
                                    padding:5
                                    size:root.width/2-200,root.height
                                    CheckBox:
                                        size_hint:.1,.1
                                        group:'sp_chk'
                                        id: sp_id
                                        active:True
                                        on_active:root.sp_change(self.active)
                                    TextInput:
                                        font_size:20
                                        id:sp_inp
                                        disabled:not sp_id.active
                                        hint_text:"Enter value of radius(m)"
                                        background_color:'#1936ff25'
                                        disabled_foreground_color:'#00ffffff'
                                        foreground_color:'#00ffffff'
                                        disabled_hint_text_color:"00ffffff"
                                        hint_text_color:"grey"
                                        font_name:"arial"
                                        font_size:25









                        BoxLayout:

                            TextInput:
                                hint_text:'00'
                                size_hint:1,.7
                                disabled:True
                                id:sp_ans
                                font_size:20
                                multiline:False
                                font_size:35
                                background_color:'#1936ff25'
                                disabled_foreground_color:'#00ffffff'
                                #color:"#e2ff19ff"
                    BoxLayout:
                        orientation:'vertical'
                        BoxLayout:
                            orientation:'horizontal'
                            size_hint:1,.2
                            Button:
                                text:'CE'
                                on_press:root. sp_all_clr()
                                background_color:'#963232ff'
                                color:'#ff1919ff'
                                font_size:45
                            Button:
                                text:'C'
                                on_press:root.sp_back()
                                background_color:'#713232ff'
                                color:'#ff3232ff'
                                font_size:45
                        GridLayout:
                            cols:3
                            rows:4
                            #row1
                            Button:
                                text:'7'
                                on_press:root.get_value_sp('7')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'8'
                                on_press:root.get_value_sp('8')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'9'
                                on_press:root.get_value_sp('9')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            #row2
                            Button:
                                text:'4'
                                on_press:root.get_value_sp('4')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'5'
                                on_press:root.get_value_sp('5')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'6'
                                on_press:root.get_value_sp('6')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            #row3
                            Button:
                                text:'1'
                                on_press:root.get_value_sp('7')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45
                            Button:
                                text:'2'
                                on_press:root.get_value_sp('2')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'3'
                                on_press:root.get_value_sp('3')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            #row4
                            Button:
                                text:'0'
                                on_press:root.get_value_sp('0')
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'.'
                                on_press:root.sp_dot()
                                background_color:'#1d0026ff'
                                color:'#00ffffff'
                                font_size:45

                            Button:
                                text:'='
                                on_press:root.sp_ans()
                                background_color:'#0569ff68'
                                color:'#00ffffff'
                                font_size:45





                Button:
                    text:'Back'
                    size_hint:1,.15
                    background_color:"#1954c787"
                    font_size:40
                    on_release:
                        app.root.current='second'
                        root.manager.transition.direction='right'
                    on_release:root.ids.sp_ans.text=""
                    on_release:root.ids.sp_inp.text=""
                    on_release:root.ids.sp_id.active=True

                    on_press:
                        root.ids.tra_inp.text=''
                        root.ids.tra_inp1.text=''
                        root.ids.tra_inp2.text=''
                        root.ids.tra_ans.text=''
                        root.ids.tra_chk.active=True
                        root.ids.inpr.text=''
                        root.ids.inpr1.text=''
                        root.ids.rans.text=''
                        root.ids.rchk.active=True
                        root.ids.a.text=''
                        root.ids.b.text=''
                        root.ids.c.text=''
                        root.ids.ans.text=''
                        root.ids.chk.active=True

        #TabbedPanelItem:square




    





#  CAL WINDOW
<CalWindow>:
    name:'calc'

    BoxLayout:
        orientation:'vertical'
        Button:
            text:'back'
            size_hint:1,.15
            background_color:"#1954c787"
            font_size:40
            on_press:root.ids.cal_inp.text=''
            on_release:


                app.root.current='second'
                root.manager.transition.direction='right'

        TextInput:

            size_hint:1,.2
            halign:'right'
            font_size:40
            multiline:False
            id:cal_inp
            text:''
            background_color:'#1936ff25'
            foreground_color:'#00ffffff'
        GridLayout:
            cols:8
            rows:5
            #row
            Button:
                text:'x³'
                font_size:35
                on_press:root.cube()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'x²'
                font_size:35
                on_press:root.square()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'sin'
                font_size:30
                on_press:root.sine()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'cos'
                font_size:30
                on_press:root.cosine()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45

            Button:
                text:'tan'
                font_size:30
                on_press:root.tangent()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'CE'
                font_size:30
                on_press:root.all_clr()
                background_color:'#963232ff'
                color:'#ff1919ff'
                font_size:45
            Button:
                text:u'\u00AB'
                font_size:50
                on_press:root.back()
                background_color:'#713232ff'
                color:'#ff3232ff'
                font_size:45
            Button:
                text:'/'
                font_size:30
                on_press:root.signs('/')
                background_color:'#19aaff86'
                color:'#00ffffff'
                font_size:45
            ###################################################
            Button:
                markup:True
                text:'sin[sup][b]-1[/b][/sup]'
                font_size:30
                on_press:root.sine_inv()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                markup:True
                text:"cos[sup][b]-1[/b][/sup]"
                font_size:30
                on_press:root.cosine_inv()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45

            Button:
                markup:True
                text:'tan[sup][b]-1[/b][/sup]'
                font_size:30
                on_press:root.tangent_inv()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'log'
                font_size:30
                on_press:root.log()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                markup:True
            
                text:'x[b][sup]y[/b][/sup]'
                font_size:30
                on_press:root.get_value('^')
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'√'
                font_size:35
                on_press:root.square_root()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:u"\u00B3"+'√'
                font_size:30
                on_press:root.cube_root()
                font_name:'arial'
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'*'
                font_size:30
                on_press:root.signs('*')
                background_color:'#19aaff86'
                color:'#00ffffff'
                font_size:45
            ###################################################

            Button:
                text:'1/x'
                font_size:30
                on_press:root.one_over()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'sinh'
                font_size:30
                on_press:root.sinh()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'%'
                font_size:30
                on_press:root.percent()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'±'
                font_size:30
                on_press:root.posneg()
                background_color:'#0569ff68'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'7'
                font_size:30
                on_press:root.get_value('7')
                background_color:'#0569ff68'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'8'
                font_size:30
                on_press:root.get_value('8')
                background_color:'#0569ff68'
                color:'#00ffffff'
                font_size:45

            Button:
                text:'9'
                font_size:30
                on_press:root.get_value('9')
                background_color:'#0569ff68'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'-'
                font_size:30
                on_press:root.signs('-')
                background_color:'#19aaff86'
                color:'#00ffffff'
                font_size:45
            ###################################################

            Button:
                markup:True
                text:'x[sup][b]10[/b][/sup]'
                font_size:30
                on_press:root.x_tenpow()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'cosh'
                font_size:30
                on_press:root.cosh()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:')'
                font_size:30
                on_press:root.get_value(')')
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45

            Button:
                text:'.'
                font_size:30
                on_press:root.dot()
                background_color:'#0569ff68'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'4'
                font_size:30
                on_press:root.get_value('4')
                background_color:'#0569ff68'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'5'
                font_size:30
                on_press:root.get_value('5')
                background_color:'#0569ff68'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'6'
                font_size:30
                on_press:root.get_value('6')
                background_color:'#0569ff68'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'+'
                font_size:30
                on_press:root.signs('+')
                background_color:'#19aaff86'
                color:'#00ffffff'
                font_size:45
            ###################################################
            Button:
                text:'π'
                font_size:30
                on_press:root.pi()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'tanh'
                font_size:30
                on_press:root.tanh()
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45

            Button:
                text:'('
                font_size:30
                on_press:root.get_value('(')
                background_color:'#1d0026ff'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'0'
                font_size:30
                on_press:root.get_value('0')
                background_color:'#0569ff68'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'1'
                font_size:30
                on_press:root.get_value('1')
                background_color:'#0569ff68'
                color:'#00ffffff'
                font_size:45
            Button:
                text:'2'
                font_size:30
                on_press:root.get_value('2')
                background_color:'#0569ff68'
                color:'#00ffffff'
                font_size:45

            Button:
                text:'3'
                font_size:30
                on_press:root.get_value('3')
                background_color:'#0569ff68'
                color:'#00ffffff'
                font_size:45


            Button:
                text:'='
                font_size:30
                on_press:root.answer()
                background_color:'#1988ffff'
                color:'#00ffffff'
                font_size:45
#THIRD WINDOW
<ThirdWindow>:
    name:'third'


    Button:
        text:'c'
        on_release:
            app.root.current='first'
            root.manager.transition.direction='right'
 #FORTH WINDOW
<FourthWindow>:
    name:'fourth'
    BoxLayout:
        orientation:'vertical'
        Label:
            text:'To enter a number, press the corresponding digits on the keypad or use the keyboard.'
        Label:
            text:'To enter a decimal point, press the “.” button on the keypad or use the keyboard.'
        Label:
            text:'To enter a negative number, press the “+/-” button on the keypad or use the keyboard before entering the number.'

        Label:
            text:'To perform an operation, press the corresponding button on the keypad or use the keyboard after entering the first number.\n For example, to add two numbers, press the “+” button after entering the first number.'
        Label:
            text:'To enter the second number, press the corresponding digits on the keypad or use the keyboard after pressing the operation button.'
        Label:
            text:'To get the result, press the “=” button on the keypad or use the keyboard after entering the second number. The result will be displayed on the screen.'
        BoxLayout:
            Button:
                size_hint:1,1
                text:'Back'
                background_color:"#1954c787"
                font_size:40
                on_release:
                    app.root.current='first'
                    root.manager.transition.direction='right'
# FIFTH WINDOW
<FifthWindow>:
    name:'fifth'
    Button:
        text:'e'
        on_release:
            app.root.current='first'
            root.manager.transition.direction='right'
# SIXTH WINDOW
<SixthWindow>:
    name:'sixth'
    BoxLayout:
        spacing_y:0
        orientation:"vertical"
        Label:
            text:"About this app"
        Label:
            text:"This app is a powerful and versatile tool for anyone who needs to solve problems involving mathematics, especially geometry\n and trigonometry. With this app, you can:"
        Label:
            text:"Calculate the areas of various plane figures, such as circles, triangles, rectangles, polygons, etc. "
        Label:
            text:"Solve trigonometric equations and expressions using the values of trigonometric functions (sine, cosine, tangent, etc.)"
        Label:
            text:'Perform scientific calculations using the built-in calculator that supports arithmetic operations, decimals, \npercentages, powers, roots, logarithms, exponentials, factorials, and more.\n You can also use parentheses and constants to organize your calculations.'
        Label:
            text:'This app is designed to be user-friendly, accurate, and reliable. You can enter your inputs using the keyboard or the touch screen.\n You can also see the steps and explanations for each calculation, as well as the graphical representation of the figures.\n You can save your results and share them with others'
        Label:
            text:'To delete the last digit or operation entered, press the “C” button on the keypad or use the keyboard. This will remove only one character from the screen.'
        Label:
            text:'To clear the screen, press the “CE” button on the keypad or use the keyboard. This will erase all the numbers and operations entered so far.'




        BoxLayout
            Button:
                text:'back'
                size_hint:1,1
                background_color:"#1954c787"
                font_size:40
                on_release:
                    app.root.current='first'
                    root.manager.transition.direction='right'
